print("Hello World!")
print("Hello Again")
print("I like typing this. ")
print('Yay! Printing. ')
print("I'd much rather you 'not' .")
print('I "said" do not touch this.')
print("printed an new line example 1-a")